### ISSUE TITLE
missing DecodeFrame entries

### ISSUE THREAD

**Issue by jblazeg** [xerootg/esp32_tp20_datalogger#3]
I got a car which asks for id 97 (0x61) in the "DecodeFrame" function (file diag.c). Any chance you can provide this as well?

**Comment by xerootg** [comment]
I don't have that handy, do you have any ideas of what it's supposed to represent? Do you have example values? I might be able to help guess, but my usual source for conversion factors is kwp1281. There used to be a page that had all the common conversion factors, but it seems to be gone.

**Comment by jblazeg** [comment]
Thats exhaust gas temperature on a Scirocco MK3. I dont have any value pairs right now.

**Comment by xerootg** [comment]
Ok, then that conversion factor should be something we can find, try this
list:
https://github.com/ibanezgomez/FISBlocks/blob/511968e726c766aa5f79a5dcd226ce211f87ba0a/KWP.cpp#L103

I wrote this project just to find out that my ecu doesn't support tp2.0.
I'm stuck with k-line even though I have canbus for things like the dash
and I have an edc16, which supported tp2.0 on the non NAR cars. it took me
so long to figure out how tp2.0 worked that I wanted to share it in case
someone else needed it. That said, the vcds definition files for measuring
blocks, I'm pretty sure include the units associated with a block. Maybe
you can combine the two to find the right values. I can try to find it, but
it's gonna be a while before I have time to dig in. Sorry, I just don't
have much to help other than pointing you somewhere else.

**Comment by jblazeg** [comment]
In the link it goes only up to 70 - i need 97. But thanks for your effort. Highly appreciate.

**Comment by xerootg** [comment]
I understand that it doesn't share the same number, but from my understanding, the conversion factor to get to the listed unit is what is important. Volkswagen has "standard" blocks, but then sometimes they had custom blocks unshared with any other car and they would use the same conversion factor but as a different measurement number. If you look at that chart of units, they have conversion factors associated. You should be able to figure out what conversion factor applies based off the unit listed in the VCDS label file for your car. For example, case 5 in that chart - `a*(b-100)*.1`. I suspect you need to modify one to get the correct range such as `a*(b-100)` since the max value of case 5 is `3952.5`. It's just an offset. Is the measurement block your looking for supported by vcds? As in, does it show units when you look at it? Or is it just a number with no label? Another option is to look at a dump of your ecu with the correct damos/a2l, there's a table of measurements and the bosch conversion factor number and figure out if there's a shared factor with a different value that we already have.
